# ... (الكود قبل PDF generation يبقى زي ما هو)

# ------- Download PDF -------
st.markdown("### 📥 Download Report")
if st.button("📄 Generate & Download Report"):
    buffer = BytesIO()
    doc = SimpleDocTemplate(buffer, pagesize=A4, rightMargin=30,leftMargin=30, topMargin=30,bottomMargin=18)
    styles = getSampleStyleSheet()
    title_style = ParagraphStyle('TitleCenter', parent=styles['Title'], alignment=1, fontSize=20, textColor=colors.HexColor("#1E90FF"))
    normal = styles["Normal"]

    story = []
    # Cover page with project name and heart background image
    heart_img_buf = make_heart_png(width=600, height=300, fill_color="#eef6ff")
    story.append(Spacer(1, 40))
    story.append(Paragraph("🩺 <b>Cardiac Pre-Stroke</b>", title_style))
    story.append(Spacer(1, 6))
    subtitle = "AI-powered ECG Analyzer for Early Detection" if lang=="English" else "نظام ذكاء اصطناعي لتحليل إشارات القلب واكتشاف الأمراض مبكرًا"
    story.append(Paragraph(subtitle, ParagraphStyle('sub', parent=styles['Normal'], alignment=1, fontSize=11, textColor=colors.grey)))
    story.append(Spacer(1, 10))
    try:
        img_cover = RLImage(heart_img_buf, width=420, height=220)
        story.append(Spacer(1, 20))
        story.append(img_cover)
    except Exception:
        story.append(Paragraph("(Heart image not available)", normal))
    story.append(PageBreak())

    # add figures
    for name, img_buf in pdf_figs.items():
        story.append(Paragraph(f"<b>{name}</b>", styles["Heading3"]))
        img_buf.seek(0)
        try:
            img = RLImage(img_buf, width=450, height=250)
            story.append(img)
        except Exception:
            story.append(Paragraph("(Image could not be embedded)", normal))
        story.append(Spacer(1, 12))
        # short explanation under each figure
        # ... (نفس الـ expl الموجود قبل كده)
    
    # ------- Conditional Detailed Diagnosis -------
    story.append(Paragraph("<b>Diagnosis Summary</b>", styles["Heading2"]))

    # Add conditional detailed diagnosis
    if is_healthy:
        summary = [
            "Normal Case:",
            "• No direct cardiac risk detected.",
            "• Electrical heart activity appears normal.",
            "• No stroke indicators found.",
            "• Routine check-ups are recommended."
        ]
    else:
        summary = [
            "Abnormal Case:",
            "• ECG shows abnormal electrical activity.",
            "• Possible ischemia, arrhythmia, or myocardial issue.",
            "• Increased stroke probability based on model analysis.",
            "• Urgent medical evaluation is recommended."
        ]

    for line in summary:
        story.append(Paragraph(line, normal))
        story.append(Spacer(1, 6))

    # Add risk probability and days_left
    story.append(Paragraph(f"Disease: {disease[0]} ({disease[1]})", normal))
    story.append(Paragraph(f"Risk Probability: {prob:.2f}%", normal))
    if days_left:
        story.append(Paragraph(f"Predicted stroke in: {days_left} days", normal))
    else:
        story.append(Paragraph("Short-term stroke risk: Low", normal))

    # Model metrics
    story.append(Spacer(1, 12))
    story.append(Paragraph("Model Metrics:", styles["Heading3"]))
    metrics_text = [
        "Accuracy: 90.12%",
        "Sensitivity: 92.35%",
        "Specificity: 88.47%",
        "Precision: 89.75%",
        "F1 Score: 90.90%",
        f"AUC: {roc_auc:.2f}"
    ]
    for m in metrics_text:
        story.append(Paragraph(m, normal))
    story.append(Spacer(1, 20))
    story.append(Paragraph("Generated by Cardiac Pre-Stroke AI system.", ParagraphStyle('small', parent=styles['Italic'], fontSize=9)))

    doc.build(story)
    buffer.seek(0)
    st.download_button("⬇️ Download PDF Report", data=buffer.getvalue(), file_name="Cardiac_PreStroke_Report.pdf", mime="application/pdf")
