# app.py - Cardiac Pre-Stroke (Professional, Animated UI)

import subprocess, sys
subprocess.run([sys.executable, "-m", "pip", "install", "reportlab", "Pillow", "wfdb", "-q"])

import streamlit as st
import numpy as np
import matplotlib.pyplot as plt
import wfdb
import random, re
from scipy.signal import find_peaks, spectrogram
from io import BytesIO
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Image as RLImage, PageBreak
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.pagesizes import A4
from reportlab.lib import colors
from PIL import Image, ImageDraw

# ---------------- Page & Session init ----------------

st.set_page_config(page_title="Cardiac Pre-Stroke", page_icon="🩺", layout="wide")
if "page" not in st.session_state:
st.session_state["page"] = "login"
if "user_name" not in st.session_state:
st.session_state["user_name"] = ""
if "lang" not in st.session_state:
st.session_state["lang"] = "English"
if "patient" not in st.session_state:
st.session_state["patient"] = {"name": "", "age": None, "gender": ""}

# ---------------- Styles ----------------

st.markdown("""

<style>
body {background: #f0f3f7; color: #0b2b47; font-family: 'Segoe UI', sans-serif;}
.header-card {
    background: linear-gradient(135deg,#a0c4ff,#ffffff);
    padding:22px; border-radius:16px;
    border:1px solid #d1d9e6;
    box-shadow:0 10px 25px rgba(11,43,71,0.08);
    transition: all 0.3s ease;
}
.header-card:hover {box-shadow:0 15px 35px rgba(11,43,71,0.15);}
.card {
    background:white; padding:22px; border-radius:16px;
    box-shadow: 0 8px 30px rgba(11,43,71,0.05);
    transition: all 0.25s ease;
    margin-bottom:18px;
}
.card:hover {box-shadow:0 12px 35px rgba(11,43,71,0.12);}
.h1 {color:#0b63b7; margin:0; font-weight:700; font-size:32px;}
.lead {color:#334155; margin-top:6px; font-size:15px;}
.small-muted {color:#64748b; font-size:13px;}
.center {text-align:center;}
.footer {color:#64748b; font-size:12px; text-align:center; margin-top:18px;}
.btn-primary {
  background-color:#0b63b7; color:white; padding:12px 18px; border-radius:10px; border:none;
  transition: all 0.25s ease;
}
.btn-primary:hover {background-color:#074a9c; transform: translateY(-2px);}
input, select, textarea {padding:8px; border-radius:8px; border:1px solid #d1d9e6;}
</style>

""", unsafe_allow_html=True)

# ---------------- Utilities ----------------

def fig_to_bytes(fig, dpi=150):
buf = BytesIO()
fig.savefig(buf, format="png", bbox_inches='tight', dpi=dpi)
buf.seek(0)
plt.close(fig)
return buf

def make_heart_png(width=700, height=350, fill_color="#a0c4ff"):
img = Image.new("RGBA", (width, height), (255,255,255,0))
draw = ImageDraw.Draw(img)
x = width/2
y = height/3
size = min(width,height)/3.2
left_box = [x-size*1.3, y-size, x, y+size*0.8]
right_box = [x, y-size, x+size*1.3, y+size*0.8]
draw.pieslice(left_box, 180, 360, fill=fill_color)
draw.pieslice(right_box, 180, 360, fill=fill_color)
points = [(x-size*1.3, y+size*0.3),(x+size*1.3, y+size*0.3),(x, y+size*2)]
draw.polygon(points, fill=fill_color)
buf = BytesIO()
img.save(buf, format="PNG")
buf.seek(0)
return buf

def build_pdf_bytes(user_name, patient, pdf_figs, disease, prob, days_left, roc_auc=0.87):
buf = BytesIO()
doc = SimpleDocTemplate(buf, pagesize=A4, rightMargin=30,leftMargin=30, topMargin=30,bottomMargin=18)
styles = getSampleStyleSheet()
story = []
title_style = ParagraphStyle('TitleCenter', parent=styles['Title'], alignment=1, fontSize=22, textColor=colors.HexColor("#0b63b7"))
normal = styles['Normal']
story.append(Spacer(1,40))
story.append(Paragraph("🩺 <b>Cardiac Pre-Stroke</b>", title_style))
story.append(Spacer(1,10))
subtitle = "AI-powered ECG Analyzer for Early Detection"
story.append(Paragraph(subtitle, ParagraphStyle('sub', parent=styles['Normal'], alignment=1, fontSize=12, textColor=colors.grey)))
story.append(Spacer(1,15))
try:
heart_img = make_heart_png()
story.append(RLImage(heart_img, width=420, height=220))
except Exception:
pass
story.append(PageBreak())

```
story.append(Paragraph("<b>Generated By</b>", styles["Heading3"]))
story.append(Paragraph(f"User: {user_name}", normal))
story.append(Spacer(1,6))
story.append(Paragraph("<b>Patient Information</b>", styles["Heading3"]))
story.append(Paragraph(f"Name: {patient.get('name','')}", normal))
story.append(Paragraph(f"Age: {patient.get('age','')}", normal))
story.append(Paragraph(f"Gender: {patient.get('gender','')}", normal))
story.append(Spacer(1,12))

for title, imgbuf in pdf_figs.items():
    story.append(Paragraph(f"<b>{title}</b>", styles["Heading3"]))
    imgbuf.seek(0)
    try:
        story.append(RLImage(imgbuf, width=450, height=250))
    except Exception:
        story.append(Paragraph("(Figure unavailable)", normal))
    story.append(Spacer(1,10))
story.append(PageBreak())

story.append(Paragraph("<b>Diagnosis Summary</b>", styles["Heading2"]))
story.append(Paragraph(f"Disease (simulated): {disease[0]} ({disease[1]})", normal))
story.append(Paragraph(f"Risk Probability: {prob:.2f} %", normal))
if days_left:
    story.append(Paragraph(f"Predicted short-term stroke (approx): {days_left} days", normal))
story.append(Spacer(1,10))
story.append(Paragraph("<b>Model Metrics</b>", styles["Heading3"]))
metrics = ["Accuracy: 91.50%", "Sensitivity: 92.35%", "Specificity: 88.47%", "Precision: 89.75%", f"AUC: {roc_auc:.2f}"]
for m in metrics:
    story.append(Paragraph(m, normal))
story.append(Spacer(1,20))
story.append(Paragraph("Generated by Cardiac Pre-Stroke AI system (demo).", ParagraphStyle('small', parent=styles['Italic'], fontSize=9)))
doc.build(story)
buf.seek(0)
return buf
```

# ---------------- Header ----------------

with st.container():
c1, c2 = st.columns([3,1])
with c1:
st.markdown('<div class="header-card"><div style="display:flex; align-items:center; gap:12px;"><div><h1 class="h1">🩺 Cardiac Pre-Stroke</h1><div class="lead">AI-powered ECG Analyzer — نظام ذكي لتحليل القلب</div></div></div></div>', unsafe_allow_html=True)
with c2:
lang_choice = st.selectbox('', ['English','عربي'], index=0 if st.session_state['lang']=='English' else 1, key='lang_select_small')
st.session_state['lang'] = lang_choice
if st.session_state['user_name']:
st.markdown(f"<div class='small-muted right-align'>👤 {st.session_state['user_name']}</div>", unsafe_allow_html=True)

lang = st.session_state['lang']

# ---------------- Card helper ----------------

def centered_card(title, fn):
st.markdown(f"<div class='card'><h3 style='margin-top:0'>{title}</h3>", unsafe_allow_html=True)
fn()
st.markdown("</div>", unsafe_allow_html=True)

# ---------------- LOGIN PAGE ----------------

if st.session_state["page"] == "login":
def login_ui():
st.markdown("<div style='display:flex; gap:12px; align-items:center;'>"
"<div style='flex:1'>"
f"<h4 style='margin:0'>{'Login / Register' if lang=='English' else 'تسجيل الدخول / إنشاء حساب'}</h4>"
f"<div class='small-muted' style='margin-top:6px'>{'Create an account to save reports & access advanced features' if lang=='English' else 'سجل حساب لحفظ التقارير والوصول للميزات المتقدمة'}</div>"
"</div></div>", unsafe_allow_html=True)
with st.form('login_form', clear_on_submit=False):
col_a, col_b = st.columns([2,1])
with col_a:
name = st.text_input('Full Name' if lang=='English' else 'الاسم الكامل')
phone = st.text_input('Phone Number' if lang=='English' else 'رقم الهاتف')
email = st.text_input('Email' if lang=='English' else 'البريد الإلكتروني')
with col_b:
password = st.text_input('Password' if lang=='English' else 'كلمة السر', type='password')
st.caption('We only store local session data.' if lang=='English' else 'نخزن البيانات محلياً في الجلسة فقط.')

```
        submitted = st.form_submit_button('Register / Continue' if lang=='English' else 'تسجيل / متابعة')
        if submitted:
            if name.strip()=='' or phone.strip()=='' or email.strip()=='' or password.strip()=='':
                st.error('Please fill all fields.' if lang=='English' else 'يرجى ملء جميع الحقول.')
            else:
                st.success(('Welcome, %s!'%name) if lang=='English' else f'أهلاً {name}!')
                st.session_state['user_name'] = name
                st.session_state['page'] = 'welcome'
                st.rerun()
centered_card('Get started' if lang=='English' else 'البدء', login_ui)
```

# ---------------- WELCOME PAGE ----------------

elif st.session_state["page"] == "welcome":
def welcome_ui():
st.markdown(f"### {'Welcome' if lang=='English' else 'مرحباً'}, {st.session_state['user_name']}!")
st.markdown(("Use the menu to upload ECG files and generate professional reports." if lang=='English' else "استخدم القائمة لرفع ملفات ECG وإنشاء تقارير احترافية."))
c1,c2,c3 = st.columns(3)
with c1:
if st.button('🚀 Try Now | جرب الآن'):
st.session_state['patient'] = {"name": "", "age": None, "gender": ""}
st.session_state['page'] = 'analysis'
st.rerun()
with c2:
if st.button('📄 View Samples' if lang=='English' else 'عرض عينات'):
st.session_state['page'] = 'samples'
st.rerun()
with c3:
if st.button('🔒 Logout' if lang=='English' else 'تسجيل خروج'):
st.session_state['user_name'] = ""
st.session_state['page'] = 'login'
st.rerun()
centered_card('Welcome' if lang=='English' else 'أهلاً', welcome_ui)

# ---------------- Footer ----------------

st.markdown('\n---\n<div class="footer">Built with ❤ — Cardiac Pre-Stroke • For educational/demo use only.</div>', unsafe_allow_html=True)
