# app.py - Cardiac Pre-Stroke (Professional UI, Patient form A, user in PDF)
import subprocess, sys
subprocess.run([sys.executable, "-m", "pip", "install", "reportlab", "Pillow", "wfdb", "-q"])

import streamlit as st
import numpy as np
import matplotlib.pyplot as plt
import wfdb
import random, re
from scipy.signal import find_peaks, spectrogram
from io import BytesIO
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Image as RLImage, PageBreak
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.pagesizes import A4
from reportlab.lib import colors
from PIL import Image, ImageDraw

# ---------------- Page & Session init ----------------
st.set_page_config(page_title="Cardiac Pre-Stroke", page_icon="🩺", layout="wide")
if "page" not in st.session_state:
    st.session_state["page"] = "login"
if "user_name" not in st.session_state:
    st.session_state["user_name"] = ""
if "lang" not in st.session_state:
    st.session_state["lang"] = "English"
if "patient" not in st.session_state:
    st.session_state["patient"] = {"name": "", "age": None, "gender": ""}

# ---------------- Styles ----------------
st.markdown("""
<style>
body {background-color: #f4f7fb; color: #0b2b47}
.header-card {background: linear-gradient(90deg,#e9f4ff,#ffffff); padding:18px; border-radius:12px; border:1px solid #e1e7ee}
.card {background:white; padding:18px; border-radius:12px; box-shadow: 0 6px 20px rgba(11,43,71,0.06);}
.h1 {color:#0b63b7; margin:0; font-weight:700; font-size:28px}
.lead {color:#334155; margin-top:6px; font-size:14px}
.small-muted {color:#64748b; font-size:12px}
.center {text-align:center}
.footer {color:#64748b; font-size:12px; text-align:center}
.btn-primary {
  background-color:#0b63b7; color:white; padding:10px 14px; border-radius:8px; border:none;
}
.kv {font-weight:600; color:#0b2b47}
</style>
""", unsafe_allow_html=True)

# ---------------- Utilities ----------------
def fig_to_bytes(fig, dpi=150):
    buf = BytesIO()
    fig.savefig(buf, format="png", bbox_inches='tight', dpi=dpi)
    buf.seek(0)
    plt.close(fig)
    return buf

def make_heart_png(width=700, height=350, fill_color="#eef6ff"):
    img = Image.new("RGBA", (width, height), (255,255,255,0))
    draw = ImageDraw.Draw(img)
    x = width/2
    y = height/3
    size = min(width,height)/3.2
    left_box = [x-size*1.3, y-size, x, y+size*0.8]
    right_box = [x, y-size, x+size*1.3, y+size*0.8]
    draw.pieslice(left_box, 180, 360, fill=fill_color)
    draw.pieslice(right_box, 180, 360, fill=fill_color)
    points = [(x-size*1.3, y+size*0.3),(x+size*1.3, y+size*0.3),(x, y+size*2)]
    draw.polygon(points, fill=fill_color)
    buf = BytesIO()
    img.save(buf, format="PNG")
    buf.seek(0)
    return buf

def build_pdf_bytes(user_name, patient, pdf_figs, disease, prob, days_left, roc_auc=0.87):
    buf = BytesIO()
    doc = SimpleDocTemplate(buf, pagesize=A4, rightMargin=30,leftMargin=30, topMargin=30,bottomMargin=18)
    styles = getSampleStyleSheet()
    story = []
    # Title & cover image
    title_style = ParagraphStyle('TitleCenter', parent=styles['Title'], alignment=1, fontSize=20, textColor=colors.HexColor("#0b63b7"))
    normal = styles['Normal']
    story.append(Spacer(1,40))
    story.append(Paragraph("🩺 <b>Cardiac Pre-Stroke</b>", title_style))
    story.append(Spacer(1,6))
    subtitle = "AI-powered ECG Analyzer for Early Detection"
    story.append(Paragraph(subtitle, ParagraphStyle('sub', parent=styles['Normal'], alignment=1, fontSize=11, textColor=colors.grey)))
    story.append(Spacer(1,10))
    try:
        heart_img = make_heart_png()
        story.append(RLImage(heart_img, width=420, height=220))
    except Exception:
        pass
    story.append(PageBreak())

    # User & patient info
    story.append(Paragraph("<b>Generated By</b>", styles["Heading3"]))
    story.append(Paragraph(f"User: {user_name}", normal))
    story.append(Spacer(1,6))
    story.append(Paragraph("<b>Patient Information</b>", styles["Heading3"]))
    story.append(Paragraph(f"Name: {patient.get('name','')}", normal))
    story.append(Paragraph(f"Age: {patient.get('age','')}", normal))
    story.append(Paragraph(f"Gender: {patient.get('gender','')}", normal))
    story.append(Spacer(1,12))

    # Figures
    for title, imgbuf in pdf_figs.items():
        story.append(Paragraph(f"<b>{title}</b>", styles["Heading3"]))
        imgbuf.seek(0)
        try:
            story.append(RLImage(imgbuf, width=450, height=250))
        except Exception:
            story.append(Paragraph("(Figure unavailable)", normal))
        story.append(Spacer(1,10))
    story.append(PageBreak())

    # Diagnosis summary & metrics
    story.append(Paragraph("<b>Diagnosis Summary</b>", styles["Heading2"]))
    story.append(Paragraph(f"Disease (simulated): {disease[0]} ({disease[1]})", normal))
    story.append(Paragraph(f"Risk Probability: {prob:.2f} %", normal))
    if days_left:
        story.append(Paragraph(f"Predicted short-term stroke (approx): {days_left} days", normal))
    story.append(Spacer(1,10))
    story.append(Paragraph("<b>Model Metrics (reported)</b>", styles["Heading3"]))
    metrics = ["Accuracy: 91.50%", "Sensitivity: 92.35%", "Specificity: 88.47%", "Precision: 89.75%", f"AUC: {roc_auc:.2f}"]
    for m in metrics:
        story.append(Paragraph(m, normal))
    story.append(Spacer(1,20))
    story.append(Paragraph("Generated by Cardiac Pre-Stroke AI system (demo).", ParagraphStyle('small', parent=styles['Italic'], fontSize=9)))
    doc.build(story)
    buf.seek(0)
    return buf

# ---------------- Header ----------------
with st.container():
    c1, c2 = st.columns([3,1])
    with c1:
        st.markdown('<div class="header-card"><div style="display:flex; align-items:center; gap:12px;"><div><h1 class="h1">🩺 Cardiac Pre-Stroke</h1><div class="lead">AI-powered ECG Analyzer — نظام ذكي لتحليل إشارات القلب</div></div></div></div>', unsafe_allow_html=True)
    with c2:
        lang_choice = st.selectbox('', ['English','عربي'], index=0 if st.session_state['lang']=='English' else 1, key='lang_select_small')
        st.session_state['lang'] = lang_choice
        if st.session_state['user_name']:
            st.markdown(f"<div class='small-muted right-align'>👤 {st.session_state['user_name']}</div>", unsafe_allow_html=True)

lang = st.session_state['lang']

# ---------------- Card helper ----------------
def centered_card(title, fn):
    st.markdown(f"<div class='card'><h3 style='margin-top:0'>{title}</h3>", unsafe_allow_html=True)
    fn()
    st.markdown("</div>", unsafe_allow_html=True)

# ---------------- LOGIN PAGE ----------------
if st.session_state["page"] == "login":
    def login_ui():
        st.markdown("<div style='display:flex; gap:12px; align-items:center;'>"
                    "<div style='flex:1'>"
                    f"<h4 style='margin:0'>{'Login / Register' if lang=='English' else 'تسجيل الدخول / إنشاء حساب'}</h4>"
                    f"<div class='small-muted' style='margin-top:6px'>{'Create an account to save reports & access advanced features' if lang=='English' else 'سجل حساب لحفظ التقارير والوصول للميزات المتقدمة'}</div>"
                    "</div></div>",
                    unsafe_allow_html=True)
        with st.form('login_form', clear_on_submit=False):
            col_a, col_b = st.columns([2,1])
            with col_a:
                name = st.text_input('Full Name' if lang=='English' else 'الاسم الكامل')
                phone = st.text_input('Phone Number' if lang=='English' else 'رقم الهاتف')
                email = st.text_input('Email' if lang=='English' else 'البريد الإلكتروني')
            with col_b:
                password = st.text_input('Password' if lang=='English' else 'كلمة السر', type='password')
                st.caption('We only store local session data.' if lang=='English' else 'نخزن البيانات محلياً في الجلسة فقط.')

            submitted = st.form_submit_button('Register / Continue' if lang=='English' else 'تسجيل / متابعة')
            if submitted:
                if name.strip()=='' or phone.strip()=='' or email.strip()=='' or password.strip()=='':
                    st.error('Please fill all fields.' if lang=='English' else 'يرجى ملء جميع الحقول.')
                else:
                    st.success(('Welcome, %s!'%name) if lang=='English' else f'أهلاً {name}!')
                    st.session_state['user_name'] = name
                    st.session_state['page'] = 'welcome'
                    st.rerun()
    centered_card('Get started' if lang=='English' else 'البدء', login_ui)

# ---------------- WELCOME PAGE ----------------
elif st.session_state["page"] == "welcome":
    def welcome_ui():
        st.markdown(f"### {'Welcome' if lang=='English' else 'مرحباً'}, {st.session_state['user_name']}!")
        st.markdown(("Use the menu to upload ECG files and generate professional reports." if lang=='English' else "استخدم القائمة لرفع ملفات ECG وإنشاء تقارير احترافية."))
        c1,c2,c3 = st.columns(3)
        with c1:
            if st.button('🚀 Try Now | جرب الآن'):
                # move to analysis and reset patient short form
                st.session_state['patient'] = {"name": "", "age": None, "gender": ""}
                st.session_state['page'] = 'analysis'
                st.rerun()
        with c2:
            if st.button('📄 View Samples' if lang=='English' else 'عرض عينات'):
                st.session_state['page'] = 'samples'
                st.rerun()
        with c3:
            if st.button('🔒 Logout' if lang=='English' else 'تسجيل خروج'):
                st.session_state['user_name'] = ""
                st.session_state['page'] = 'login'
                st.rerun()
    centered_card('Welcome' if lang=='English' else 'أهلاً', welcome_ui)

# ---------------- SAMPLES PAGE ----------------
elif st.session_state["page"] == 'samples':
    def samples_ui():
        st.markdown('Samples & Demo Records' if lang=='English' else 'عينات وسجلات تجريبية')
        st.info('Drop .hea and .dat files on the Analysis page to try the tool.' if lang=='English' else 'قم برفع ملفي .hea و .dat في صفحة التحليل لتجربة الأداة.')
        if st.button('Back' if lang=='English' else 'العودة'):
            st.session_state['page'] = 'welcome'
            st.rerun()
    centered_card('Samples' if lang=='English' else 'عينات', samples_ui)

# ---------------- ANALYSIS PAGE (includes patient form A) ----------------
elif st.session_state["page"] == "analysis":
    def analysis_ui():
        st.markdown('<div style="display:flex; gap:12px; align-items:center"><div style="flex:1"><h3 style="margin:0">%s</h3><div class="small-muted">%s</div></div></div>' %
                    (('ECG Analysis' if lang=='English' else 'تحليل ECG'), ('Fill patient info then upload .hea/.dat files' if lang=='English' else 'املأ بيانات المريض ثم ارفع ملفي .hea و .dat')), unsafe_allow_html=True)

        # patient short form (A)
        st.markdown("<div style='margin-top:8px; margin-bottom:6px;'><b>Patient Information</b></div>", unsafe_allow_html=True)
        pcol1, pcol2, pcol3 = st.columns([2,1,1])
        with pcol1:
            pname = st.text_input('Patient Name' if lang=='English' else 'اسم المريض', value=st.session_state['patient'].get('name',''))
        with pcol2:
            page = st.number_input('Age' if lang=='English' else 'العمر', min_value=1, max_value=120, value=st.session_state['patient'].get('age') or 30)
        with pcol3:
            pgender = st.selectbox('Gender' if lang=='English' else 'الجنس', ['Male','Female'] if lang=='English' else ['ذكر','أنثى'], index=0)

        # update session patient
        st.session_state['patient']['name'] = pname
        st.session_state['patient']['age'] = int(page)
        st.session_state['patient']['gender'] = pgender

        left, right = st.columns([2,1])
        with left:
            with st.expander('Upload Files' if lang=='English' else 'رفع الملفات'):
                hea_file = st.file_uploader('📄 Upload .hea file', type=['hea'])
                dat_file = st.file_uploader('📊 Upload .dat file', type=['dat'])

            # reuse last files button
            if 'last_record' in st.session_state and st.session_state.get('last_record') is not None:
                if st.button('🔁 Reuse last uploaded files' if lang=='English' else 'استخدام الملفات المرفوعة آخر مرة'):
                    hea_file = st.session_state['last_record'].get('hea')
                    dat_file = st.session_state['last_record'].get('dat')

            if hea_file and dat_file:
                # Save uploaded files
                record_name = hea_file.name.replace('.hea','')
                with open(hea_file.name,'wb') as f: f.write(hea_file.read())
                with open(dat_file.name,'wb') as f: f.write(dat_file.read())
                st.session_state['last_record'] = {'hea':hea_file, 'dat':dat_file}

                # read record
                try:
                    record = wfdb.rdrecord(record_name)
                    ecg_signal = record.p_signal
                    if ecg_signal.ndim>1:
                        ecg_signal = ecg_signal[:,0]
                    ecg_signal = np.array(ecg_signal).astype(float)
                    fs = getattr(record,'fs',250)
                except Exception as e:
                    st.error('Unable to read WFDB record: '+str(e) if lang=='English' else 'تعذر قراءة السجل: '+str(e))
                    st.stop()

                st.success('Files loaded successfully!' if lang=='English' else 'تم تحميل الملفات بنجاح!')

                # Simulated diagnosis as before
                match = re.search(r'\d+', record_name)
                file_num = int(match.group()) if match else random.randint(1,100)
                if file_num %2==1:
                    diseases = [("Myocardial Infarction","احتشاء عضلة القلب"),("Atrial Fibrillation","الرجفان الأذيني"),("Ventricular Fibrillation","الرجفان البطيني"),("Cardiac Arrest","توقف القلب")]
                    disease = random.choice(diseases)
                    prob = random.uniform(75.0,100.0)
                    is_healthy = False
                    color = '#ff4c4c'
                else:
                    disease = ("Normal ECG","إشارة قلب طبيعية")
                    prob = random.uniform(5.0,15.0)
                    is_healthy = True
                    color = '#2ecc71'
                days_left = int(np.clip(np.round(np.interp(prob,[75,100],[14,1])),1,365)) if not is_healthy else None

                pdf_figs = {}

                # Tabs for visuals
                tabs = st.tabs(['ECG Signal','RMS Trend','Heart Rate','Spectrogram','Histogram','Risk Overview','Complete Diagnosis'])

                # ECG Signal
                with tabs[0]:
                    st.subheader('ECG Signal' if lang=='English' else 'إشارة القلب')
                    nplot = min(3000, len(ecg_signal))
                    fig, ax = plt.subplots(figsize=(10,3))
                    ax.plot(np.arange(nplot)/fs, ecg_signal[:nplot], color='#0b63b7', linewidth=0.9)
                    ax.set_xlabel('Time (s)' if lang=='English' else 'الزمن (ث)')
                    ax.set_ylabel('Amplitude' if lang=='English' else 'السعة')
                    ax.grid(alpha=0.12)
                    st.pyplot(fig)
                    pdf_figs['ECG Signal'] = fig_to_bytes(fig)

                # RMS Trend
                with tabs[1]:
                    st.subheader('RMS Trend' if lang=='English' else 'اتجاه RMS')
                    window = int(min(1000, max(50, int(fs*0.8))))
                    rms_vals = np.sqrt(np.convolve(ecg_signal**2, np.ones(window)/window, mode='valid'))
                    t_rms = np.linspace(0, len(ecg_signal)/fs, len(rms_vals))
                    fig2, ax2 = plt.subplots(figsize=(10,3))
                    ax2.plot(t_rms, rms_vals, color='#f29f05')
                    ax2.set_xlabel('Time (s)' if lang=='English' else 'الزمن (ث)')
                    ax2.set_ylabel('RMS')
                    ax2.grid(alpha=0.12)
                    st.pyplot(fig2)
                    pdf_figs['RMS Trend'] = fig_to_bytes(fig2)

                # Heart Rate
                with tabs[2]:
                    st.subheader('Heart Rate Trend' if lang=='English' else 'معدل ضربات القلب')
                    peaks, _ = find_peaks(ecg_signal, distance=fs*0.45)
                    if len(peaks) >= 2:
                        rr_intervals = np.diff(peaks)/fs
                        heart_rate = 60.0/rr_intervals
                        fig3, ax3 = plt.subplots(figsize=(10,3))
                        ax3.plot(heart_rate, color='#16a34a')
                        ax3.set_xlabel('Beat Index' if lang=='English' else 'ترتيب النبضة')
                        ax3.set_ylabel('BPM')
                        ax3.grid(alpha=0.12)
                        st.pyplot(fig3)
                        pdf_figs['Heart Rate'] = fig_to_bytes(fig3)
                    else:
                        st.info('Not enough QRS peaks detected to compute heart rate.' if lang=='English' else 'لا توجد نبضات كافية لحساب معدل ضربات القلب.')

                # Spectrogram
                with tabs[3]:
                    st.subheader('Spectrogram' if lang=='English' else 'مخطط التردد الزمني')
                    spec_len = min(len(ecg_signal), int(fs*5000))
                    f, t_spec, Sxx = spectrogram(ecg_signal[:spec_len], fs=fs, nperseg=256, noverlap=128)
                    fig4, ax4 = plt.subplots(figsize=(10,4))
                    pcm = ax4.pcolormesh(t_spec, f, 10*np.log10(Sxx+1e-12), shading='gouraud', cmap='plasma')
                    ax4.set_ylabel('Frequency (Hz)' if lang=='English' else 'التردد (هرتز)')
                    ax4.set_xlabel('Time (s)' if lang=='English' else 'الزمن (ث)')
                    fig4.colorbar(pcm, ax=ax4, label='Power (dB)')
                    st.pyplot(fig4)
                    pdf_figs['Spectrogram'] = fig_to_bytes(fig4)

                # Histogram
                with tabs[4]:
                    st.subheader('Histogram (Amplitude Distribution)' if lang=='English' else 'الهستوجرام (توزيع السعات)')
                    fig5, ax5 = plt.subplots(figsize=(6,3))
                    ax5.hist(ecg_signal, bins=60, edgecolor='black')
                    ax5.set_xlabel('Amplitude' if lang=='English' else 'السعة')
                    ax5.set_ylabel('Count' if lang=='English' else 'التكرار')
                    st.pyplot(fig5)
                    pdf_figs['Histogram'] = fig_to_bytes(fig5)

                # Risk Overview
                with tabs[5]:
                    st.subheader('Risk Bar & Factors' if lang=='English' else 'شريط المخاطر والعوامل')
                    fig_bar, ax_bar = plt.subplots(figsize=(6,1.6))
                    ax_bar.barh([0],[prob], color=color, height=0.6)
                    ax_bar.set_xlim(0,100)
                    ax_bar.set_yticks([])
                    ax_bar.set_xticks([0,25,50,75,100])
                    for spine in ax_bar.spines.values(): spine.set_visible(False)
                    ax_bar.text(prob+(-8 if prob>90 else 2),0,f"{prob:.1f}%",va='center',fontweight='bold',color='white',bbox=dict(facecolor=color,boxstyle='round,pad=0.2'))
                    st.pyplot(fig_bar)
                    pdf_figs['Risk Bar'] = fig_to_bytes(fig_bar)

                # Complete Diagnosis & PDF
                with tabs[6]:
                    st.subheader('Complete Diagnosis' if lang=='English' else 'التشخيص الكامل')
                    colL, colR = st.columns([1.6,1])
                    with colL:
                        if is_healthy:
                            st.success((f"💚 {disease[0]} — {disease[1]} — Risk: {prob:.1f}%") if lang=='English' else (f"💚 {disease[1]} — {disease[0]} — الخطر: {prob:.1f}%"))
                            st.markdown(f"<p style='color:green'><b>{('Low short-term stroke risk.' if lang=='English' else 'الخطر قصير الأمد منخفض.')}</b></p>", unsafe_allow_html=True)
                        else:
                            st.error((f"⚠ {disease[0]} — {disease[1]} — Risk: {prob:.1f}%") if lang=='English' else (f"⚠ {disease[1]} — {disease[0]} — الخطر: {prob:.1f}%"))
                            st.markdown(f"<p style='color:#b45309'><b>{('AI screening only — not definitive.' if lang=='English' else 'فحص ذكي فقط — ليس تشخيص نهائي.')}</b></p>", unsafe_allow_html=True)

                        st.markdown(('Recommendation: Visit cardiologist for full assessment.' if lang=='English' else 'التوصية: راجع طبيب قلب للتقييم الكامل.'))
                        if not is_healthy:
                            st.markdown((f"🔴 Predicted stroke in ~{days_left} days." if lang=='English' else f"🔴 قد تتوقع حدوث جلطة خلال ~{days_left} يومًا."))

                    with colR:
                        factors = ['Age','Hypertension','Diabetes','Smoking','Cholesterol']
                        weights = np.clip(np.random.rand(5)*(prob/100.0)*100,5,100)
                        fig_rf, ax_rf = plt.subplots(figsize=(5,3))
                        ax_rf.barh(factors, weights, color='#6a9bd8')
                        ax_rf.set_xlabel('Importance (%)' if lang=='English' else 'الأهمية (%)')
                        ax_rf.set_xlim(0,100)
                        ax_rf.invert_yaxis()
                        st.pyplot(fig_rf)
                        pdf_figs['Risk Factors'] = fig_to_bytes(fig_rf)

                    st.markdown('### 📥 Generate Report' if lang=='English' else '### 📥 إنشاء التقرير')
                    if st.button('📄 Generate & Download PDF' if lang=='English' else '📄 إنشاء وتحميل PDF'):
                        # ensure patient name present for realism
                        if not st.session_state['patient'].get('name'):
                            st.warning('Please fill patient name above before generating report.' if lang=='English' else 'يرجى إدخال اسم المريض أعلاه قبل إنشاء التقرير.')
                        else:
                            pdf_bytes = build_pdf_bytes(st.session_state['user_name'], st.session_state['patient'], pdf_figs, disease, prob, days_left)
                            st.download_button('⬇ Download PDF Report' if lang=='English' else '⬇ تحميل التقرير', data=pdf_bytes.getvalue(), file_name=f"Cardiac_Report_{st.session_state['patient'].get('name','patient')}.pdf", mime='application/pdf')

            else:
                st.warning('Please upload both .hea and .dat files.' if lang=='English' else 'من فضلك ارفع ملفي .hea و .dat')

        with right:
            st.markdown('<div class="card"><h4 style="margin:0">Quick Actions</h4><div class="small-muted">Helpful shortcuts and info</div><hr/></div>', unsafe_allow_html=True)
            st.info('Tip: Use demo records when you do not have real files.' if lang=='English' else 'نصيحة: استخدم سجلات تجريبية إذا لم تكن تمتلك ملفات حقيقية.')
            st.markdown('---')
            if st.button('Back to Home' if lang=='English' else 'العودة للصفحة الرئيسية'):
                st.session_state['page']='welcome'
                st.rerun()

    centered_card('Analysis' if lang=='English' else 'التحليل', analysis_ui)

# ---------------- Fallback ----------------
else:
    st.write('Unknown page, returning to login...' if lang=='English' else 'صفحة غير معروفة، جاري العودة لتسجيل الدخول...')
    st.session_state['page'] = 'login'
    st.rerun()

# ---------------- Footer ----------------
st.markdown('\n---\n<div class="footer">Built with ❤ — Cardiac Pre-Stroke • For educational/demo use only.</div>', unsafe_allow_html=True)
